### ISSUE TITLE
Project aborted ? 

### ISSUE THREAD

**Issue by Finch29** [soyuka/explorer#38]
Hi ! 
 Have you stop the developpement of this project or you continue ? :s

Thx ;)

**Comment by soyuka** [comment]
I first rewrote it by using angular2, api didn't change much and refactoring improved the backend. 
I still have the code but hasn't published because angular2 evolved a lot since rc5... I need to find time to take a look into this. 
Anyway I use it every day so it's not really aborted, you have an issue?

**Comment by Finch29** [comment]
OK OK 😊 I just want to take news 😉 I have no problem with your Explorer ☺️ thx for your answer
